### ISSUE TITLE
Darwin Core Hour Introduction Presentation

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc-qa#1]
Create a presentation to kick off the Darwin Core Hour series (https://www.idigbio.org/content/darwin-core-hour-webinar-series). The presentation should cover:

What inspired this series?
What are we trying to accomplish with this series?
What are some examples of topics?
Where can I send topics for discussion?
What will happen with these submissions?

**Comment by tucotuco** [comment]
Link to publicly accessible presentation added to Webinars wiki page. Check that the link opens the presentation correctly for others.

**Comment by tucotuco** [comment]
Ready for review at https://docs.google.com/presentation/d/1yc7ZtJrwmkbCaiU7fze6igMA9sQIsgRf1w19agaHfQc/edit?usp=sharing.

@debpaul Can you have a look at this? With this series introduction in place, there will not be anything that you need to do to introduce it. We were thinking it would be good to encourage people giving presentations in the series to use slides 1 and 7 from this presentation, or adaptations of them.

**Comment by debpaul** [comment]
Hi @tucotuco Aha. Thanks. It's looking good 👍 I'll still need to do an intro (Hi - Who we are, how to get around in Adobe Connect, the chat, what to expect (the survey), and format (Presentation, then open mic)).

**Comment by debpaul** [comment]
And @tucotuco need to 

1. add iDigBio logo (and other relevant logos - by all means) - to show and recognize joint community input and effort
2. add explicitly (and I'll be saying this out loud in the short intro), that another goal is to more tightly integrate the SPNHC community (data providers) with those mobilizing data (GBIF nodes, VertNet, iDigBio, Symbiota,...) with those supporting evolution of the data standards we need. Specifically thinking of SPNHC and TDWG 2017 and 2018 for this goal.

**Comment by debpaul** [comment]
@tucotuco I made a copy of the presentation - and added some bits to consider https://docs.google.com/presentation/d/1YO2eLzXVMjWARAUgPjhvWkGuyOiLg0jD5epEJkbvyds/edit?usp=sharing You and Paula have edit access.

**Comment by kcopas** [comment]
@debpaul as when and where and where you need them, here are a [variety of formats and sizes of GBIF's logos](http://gbif.org/logos) along with rationales for each.

Sorry to say I'll miss the event—even in-flight wifi en route to Brussels probably wouldn't be enough to help. But I do look forward to the recording, to say nothing of the next in the series…

**Comment by debpaul** [comment]
Thanks @kcopas I'm hoping we figure out how to show all the relevant communities - that this is a joint effort - and all are encouraged, and welcome.

**Comment by tucotuco** [comment]
Done. Available for public viewing at https://docs.google.com/presentation/d/1yc7ZtJrwmkbCaiU7fze6igMA9sQIsgRf1w19agaHfQc/edit?usp=sharing.
