### ISSUE TITLE
Move dwc examples page to this page

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-qa#105]
The Darwin Core website for a long time had a page with examples. That page has been removed for a while and will now be removed from the dwc repository (https://github.com/tdwg/dwc/issues/153). That pages _has_ been transformed to Markdown:

https://github.com/tdwg/dwc/blob/64311240eeb15c0016c858846f9adbfb91bd515d/terms/terms.md

... but should probably make it in one form or another to this repository or be marked obsolete.

**Comment by tucotuco** [comment]
The page has been move to the examples directory in this repository with commit a9c7801f6930b68ea1814917c3eb9c20c34cedf1. Will close this issue and create another one about incorporating those examples in the regular documentation in this repository.
