### ISSUE TITLE
municipality - What should I do when my location is exactly in the middle of two cities?

### ISSUE THREAD

**Issue by nnsdtr** [tdwg/dwc-qa#146]
I'm new to Darwin Core, so I apologize for the question if it is too simple.

Some of my sampling points fall over the intersection between two cities, since the points are located on a river and it is shared by these cities. I need to inform the cities where the points are, however "municipality" apparently doesn't allow the use of more than one value with the "|" separator.

Can anyone tell me what would be the best way to proceed in this situation?

**Comment by bradmROM** [comment]
From the Georeferencing Quick Guide:

Named Place Between two Places Examples:
"between Missoula and Florence, Montana",
"Entre Pampa Blanca y Pampa Vieja, Jujuy"

Calculation Type: “Error only - enter Lat/Long for the actual locality"
Locality Type: “Named place only"
Coordinates: Use the midpoint between the centers of the two named places.
Extent: The extent is half the distance between the centers of both named places.

Brad Millen, ROM

**Comment by tucotuco** [comment]
Hi Daniel,

The recommendation to not put more than one named place in the geography terms is to try to be sure that the content refers to a standard feature name. That isn't possible when there is more than one in that field. 
As a separate consideration, if the locations are very specific, they likely fall in only one jurisdiction and there wouldn't be a problem having to list them both. But if the location isn't specific enough to tell, then there is still a way not to lose information.
In a case like this, the "county" (second level subdivision, whether it is called a county or not), which is the next level less specific than "municipality", should contain the name of the administrative division that contains both of the municipalities. If the municipalities are in distinct second level administrative subdivisions, revert to the first level administrative subdivision that contains them both and leave "county" empty as well, and so on to country. 
The information about the municipalities can go in either of two places. One is to put the municipalities in the higherGeography field. The other is to concatenate it onto the locality field. When we do our cleanup processing in VertNet, we use the first of these two options, with the justification being that the information is about higher geography, and therefore apt for the higherGeography field.
Your example also mentions a river. Make sure to include that in the waterbody field.

Here is an example that I think is similar to your case, and what we would do with it in Darwin Core:
Original locality: Danube River between Adony and Lórév, Hungary

Darwin Core:
continent="Europe"
country="Hungary"
countryCode="HU"
stateProvince=null
county=null
municipality=null
waterbody="Danube"
higherGeography="Hungary | Adony and Lórév | Danube

**Comment by nnsdtr** [comment]
Thank you for your reply  @tucotuco! That solved my doubt.
