### ISSUE TITLE
Autogeneration of contact lists for admins

### ISSUE THREAD

**Issue by Barkworth** [tdwg/dwc-qa#174]
There are times it would be useful to send a message to all collections managers in a network such as OpenHerbarium, OpenZooMuseum. At present, the list has to be compiled and updated manually.  It would be great if this could be automated, with a similar ability existing for contacting classes of people with the other categories of membership in the network (image editors, taxon specialists, etc.).

**Comment by tucotuco** [comment]
Destined for Symbiota 2. Closing.
