### ISSUE TITLE
Developing research checklists from multiple sources.

### ISSUE THREAD

**Issue by Barkworth** [tdwg/dwc-qa#176]
Researchers often draw on records from multiple resources, not just those from one Symbiota network. It would be useful if it could be made possible for such researchers (or research groups) could aggregate data into a research collection. Research collections would have the following restrictions: could not be displayed; could not be uploaded to GBIF (or other aggregators). Or perhaps it could be made possible to share some records, if permission is obtained, it would be possible to add some of the records to the researcher's home network - by collection. This might persuade collection owners of the value of sharing the records they currently allow to be revealed on only to those who have paid for digitization.

**Comment by tucotuco** [comment]
Destined for Symbiota 2. Closing.

**Comment by seltmann** [comment]
@Barkworth just reopening to point out that this functionality already exists in several portals where people are creating research-oriented collections in Symbiota. 
See (https://serv.biokic.asu.edu/ecdysis/collections/index.php) and (https://symbiota.ccber.ucsb.edu/collections/index.php). Symbiota Lite, which is the version of Symbiota that supports the plant TCNs and Ecdysis has excellent dataset building capabilities.

**Comment by Barkworth** [comment]
First off - I love the checklist function in Symbiota. I think that I may not have made it clear that I want to include records that are in GBIF (yes, they can be imported) but not in a connected collection. It was hard to tell from the links which collections were providing vouchers for the checklists. That might be a good feature to add - a summary of the collections providing vouchers.  It would provide them with a bit more publicity and, to make it even better, enable collection managers to generate a list of the checklists that use their specimens.
