### ISSUE TITLE
Date issues

### ISSUE THREAD

**Issue by Barkworth** [tdwg/dwc-qa#177]
1. Range of dates: This could be more straightforward by having two fields on the data entry form, as is done for elevation range. The rule is use the lowest (earliest) value first. 
2. Dateidentified: at prseent, so far as I am aware, this is treated as a verbatim field. I recommend splitting it into 3 fields, but having it acceptable to enter only the year if the day and month are not on the label (as is usually the case).

**Comment by tucotuco** [comment]
Destined for Symbiota 2. Closing.
