### ISSUE TITLE
how to record multiple important dates

### ISSUE THREAD

**Issue by LauraPorturas** [tdwg/dwc-qa#180]
Is there a best way/standardized way to record "emergence date" for reared organisms in Darwin Core? 

Example of this type of specimen: a wasp and the gall it was reared from. The gall was collected on [eventDate], and several months later the wasp emerged from the gall. 

What field would be best to record the second date associated with this specimen?

Thanks for any advice.

**Comment by dagendresen** [comment]
I would register one Occurrence (Event) for the "collected on" and another Occurrence (Event) for "emerged from the gall" - both with the same organismID (?).

**Comment by tucotuco** [comment]
There are various other ways to do it. The simplest is to include a comment in occurrenceRemarks field. The big disadvantage of that one is that it is likely to get lost among potentially many diverse comments in that field. 

A second way is to add a dynamicProperty, which would look something like this:

{ "emergence date":"2021-08-06" } 

That would be unambiguous as long as the user of the data understands what you mean by the key "emergence date".

A third way would be to add a MeasurementOrFact record in a separate file using the [MeasurementOrFact Extension](https://tools.gbif.org/dwca-validator/extension.do?id=dwc:MeasurementOrFact). In this case the extra file must have an occurrenceID field populated to match the occurrenceID in the record for the Occurrence for the collection of the wasp. The major advantage of this approach is that you can include lots of extra [information about the measurement](https://dwc.tdwg.org/terms/#measurementorfact). The most important thing about this approach is to use a value for measurementType from a controlled vocabulary, if one exists.

**Comment by poboyski** [comment]
Hi, All. This remains a very important issue in entomology and I am hoping that something more formal can be created. It is common to collect specimens as larvae and rear them to adulthood or until a parasite/parasitoid emerges and they are "collected" again at a different life stage. We have tens of thousands of these specimens in our collection alone. We use Associated_Taxon and Association_Type for emerged parasites/parasitoids, but the adult moth is not really a parasite of itself as a caterpillar. Another formal date field (eg. Date_Emergence) would be really helpful.  - Pete

**Comment by ben-norton** [comment]
@poboyski Your explanation makes perfect sense, but there's an overarching problem. Explicitly defining types as terms is a task without end.  It would require a nearly endless number of terms to provide full coverage to all 'Event types' or 'Date Types'. As mentioned above, you could create an event with Emergence as the event type. Event type is more semantically accurate than date type. 'Emergence' describes what is happening, not how it's temporally defined.
