### ISSUE TITLE
Representing excluded synonyms in DwC

### ISSUE THREAD

**Issue by elisabeth-huellbusch** [tdwg/dwc-qa#187]
We would like to publish Checklists that include information on excluded synonyms/information on types that have been excluded from a taxon. Is there a way to represent this in DwC or should those synonyms be removed from our checklists?

**Comment by mdoering** [comment]
Can you explain this a little more, maybe with an example? Do you have a list of type material that somehow used to be associated with a taxon, but now you want to assert that some of those specimens are not considered to belong to the taxon anymore - and I assume you do not know where else?

**Comment by elisabeth-huellbusch** [comment]
This is an example from the International Code of Nomenclature for algae, fungi, and plants:

> Recommendation 47A
> 
> 47A.1. When an alteration as mentioned in [Art. 47.1](https://www.iapt-taxon.org/nomen/pages/main/art_47.html#Art47.1) has been considerable, the nature of the change may be indicated by adding such words, abbreviated where suitable, as “emendavit” (emend.) followed by the name of the author responsible for the change, “mutatis characteribus” (mut. char.), “pro parte” (p. p.), “excluso genere” or “exclusis generibus” (excl. gen.), “exclusa specie” or “exclusis speciebus” (excl. sp.), “exclusa varietate” or “exclusis varietatibus” (excl. var.), “sensu amplo” (s. ampl.), “sensu lato” (s. l.), “sensu stricto” (s. str.), etc.
> 
> Ex. 1. Phyllanthus L. emend. Müll. Arg.; Globularia cordifolia L. excl. var. (emend. Lam.).

In our lists I would like to publish this example is represented like this:
- Accepted name: Globularia cordifolia L. 
- Synonym: excl. Globularia cordifolia var. cordifolia L. emend. Lam.

My question is how to deal with such synonyms in DwC? Is there a way to provide this synonym along with the information that it is excluded from the taxon? Or will we have to remove the synonym?

**Comment by mdoering** [comment]
You would have to assign it to some other accepted name. There is no means in DwC to say this used to be a synonym and has been excluded by Lamarck.

I am not sure if I understand this case though. The autonym is excluded? Does that mean Lamarck recognized the existance of some variety and therefore also the autonym while Linne did not?

**Comment by elisabeth-huellbusch** [comment]
OK, so in the rare case that we have such a synonym we will remove it from our list.

Sorry, the example provided is probably not the best. It looks like a misapplied name to me.
