### ISSUE TITLE
Possibility to have a "title" box in the Darwin Core Hour Input Form

### ISSUE THREAD

**Issue by cgendreau** [tdwg/dwc-qa#19]
Maybe it can curated or maybe add a "title" field to the form simply to avoid a giant list of "Darwin Core Hour Input Form 2/7/2017 ..." on https://github.com/tdwg/dwc-qa/issues/

**Comment by kevinlove** [comment]
It still leaves the issue title up to the user, which is what I was trying to avoid by standardizing on the pattern used. I could do a trim on the submitted topic field... say maybe the first 40 characters?

**Comment by debpaul** [comment]
Hey @kevinlove, @tucotuco and I discussed similar idea of mine, at length. I had wanted a field something like "submit your key darwin core term" as a way to help organize the tickets.

**Comment by pzermoglio** [comment]
Problem with that is that it would leave out more general questions, ones
that have nothing to do with a particular term (which seems to be the case
in most of the submitted issues so far). Could have an option "general
question" or the like, though.

**Comment by debpaul** [comment]
maybe we have a title field (known length), and a keywords (key terms) field?

**Comment by tucotuco** [comment]
I am in favor of leaving the tagging entirely to labels added by those managing the issues. Any thing else will create chaos, I believe. Titles could still be useful, but they can also be changed to whatever desired by the repository managers as they take on issues. Is there a particular reason why the new form submission must have the same title? I DO like that they have the submission date-time.

**Comment by debpaul** [comment]
hm. Perhaps we re-visit @cgendreau idea for titles. I see this growing pile of "Darwin Core Hour Input form" - which other than the time-stamp is not too useful. Note the "form submission" label tells us the ticket came from the dwc hour input form. Maybe when you "touch" a ticket - you rename it? as @tucotuco suggests?

**Comment by debpaul** [comment]
Example https://github.com/tdwg/dwc-qa/issues/40 could change title to
> dwc:collectionCode How to use? 2/14/2017 11:48:24
simple enough to do - and makes reading through them, much more of a useful experience.

**Comment by tucotuco** [comment]
I support the idea of post-facto title editing. Let's take further discussion, if any to an issue in the site management repo

https://github.com/VertNet/dwc-qa-manage/issues

Closing this one.
