### ISSUE TITLE
Need of a field or vocabulary to document endemic status

### ISSUE THREAD

**Issue by camiplata** [tdwg/dwc-qa#195]
Information about endemic species is key for decision making, many governments use this information to declare conservation programs and areas. Also, the publishers from the community of taxonomists desire to add this information to their taxonomic checklist s

Currently, DwC is lacking a clear field(s) to document this information, [there was an attempt to include it as a vocabulary for occurrenceStatus](https://github.com/tdwg/dwc/issues/342) but it was inconclusive. 

With this issue, I kindly ask the DwC maintenance group to address this need.

I believe the adequate term to include the "endemic" label could be establishmentMeans as a more detailed specification of native.

@SIB-Colombia @EstebanMH-SiB @RicardoOrtizG

**Comment by CecSve** [comment]
+1. I was just about to create an issue on the same topic. GBIF helpdesk is asked on a regular basis how publishers can map endemism. 
  

> I believe the adequate term to include the "endemic" label could be establishmentMeans as a more detailed specification of native.

It seems GBIF users expect the label to be found as part of a controlled vocabulary in the establishmentMeans term, so it could be a good idea to include it here.

**Comment by tucotuco** [comment]
It sounds like there is a clear need for this. I recommend to follow the [protocol](https://github.com/tdwg/dwc/blob/master/.github/CONTRIBUTING.md) for a new term request. Be sure to gather the information to meet the justification criteria (i.e., that there are independent groups who have a need to share of consume these data. Also make clear in the new term template that the suggestion is for a new vocabulary term for establishmentMeans.

**Comment by CecSve** [comment]
Thank you! @camiplata let me know if I can help with this in any way.

**Comment by camiplata** [comment]
Thanks @tucotuco I just created the following issue: https://github.com/tdwg/dwc/issues/434, please let me know if the information is suficient. @CecSve does the new issue also fullfills your needs?

**Comment by tucotuco** [comment]
Thank you for submitted that change request. Closing the issue here.
