### ISSUE TITLE
Issues submitted via Google Form, how to get responses back to the submitter

### ISSUE THREAD

**Issue by kevinlove** [tdwg/dwc-qa#20]
Seems like we have discussions forming already here in the issue queue, but we need to make sure the original submitter is able to participate. Do we need to add a mechanism for this? How should this work?

**Comment by pzermoglio** [comment]
Easiest would be for submitter to have a github account and watch...? But
difficult to convince many of the advantages of that...​ Should this be a
strong recommendation for webinar attendees? Just thoughts

2017-02-07 16:47 GMT-03:00 Kevin Love <notifications@github.com>:

**Comment by kevinlove** [comment]
@pzermoglio That seems like a pretty high bar to set. At best, we could ask if the user would like to associate a github username with the submission and set to watch if provided.

We should definitely send the user an email with a link to the issue and let them decide their level of interaction after that.

**Comment by debpaul** [comment]
+1 @kevinlove with much encouragement to get github account (a friendly link).

**Comment by tucotuco** [comment]
I think real participation and all its benefits are best realized by using
a GitHub account. Perhaps we can adapt this and reference it in the REDME.md

http://vertnet.org/resources/issuetrackingguide.html

and/or include it in a video orientation to the repository, also linked in
the README.md.

**Comment by tucotuco** [comment]
Moved this issue to the DwC-QA management issue tracker so that watchers do not have to see the management side of things.

https://github.com/VertNet/dwc-qa-manage/issues/1
