### ISSUE TITLE
Is there a dwc term (or other tdwg term) for informal group?

### ISSUE THREAD

**Issue by miekeGR** [tdwg/dwc-qa#202]
I have been searching for an official tdwg term that matches this:

https://dbpedia.org/page/Informal_group_(taxonomy)
"An informal group in taxonomy is a taxonomic rank that is not well defined. This type of group can be paraphyletic or polyphyletic but is kept for ease, pending new systems of classification."

Does it exist? I have not yet been able to find one.

Thanks in advance.

**Comment by ben-norton** [comment]
Unfortunately, it does not @miekeGR . Maybe there's an alternate solution. Can you describe what you are trying to accomplish?

**Comment by miekeGR** [comment]
Hi Ben,

Thanks so much for your response. I am looking for a attribute term that can accommodate "tags" to taxa that are recognised within our database, but do not match a taxonomic or phylogenetic grouping. Some of these tags incorporate habitat, regional (location), and physical characteristics e.g. Pilbara troglofauna. 

Cheers,

Mieke

**Comment by baskaufs** [comment]
Hi Mieke,

There is the Audiovisual Core term `ac:tag` (http://rs.tdwg.org/ac/terms/tag). It was minted for tagging media items, but in theory could be used to tag any kind of resource.

Steve

**Comment by miekeGR** [comment]
Wonderful idea Steve ! I think that would work really well. 

Thanks @baskaufs and @ben-norton , your help is much appreciated.

**Comment by baskaufs** [comment]
Glad to help!
