### ISSUE TITLE
Linking occurrences to source information?

### ISSUE THREAD

**Issue by laurabrenskelle** [tdwg/dwc-qa#207]
What would be the best practice for linking to another archival source where more data about an occurrence could be accessed by users? Particularly for animal telemetry data. Occurrences based on these data are in OBIS, but if we wanted to provide a DOI to where these data are archived at NCEI (if someone wanted to look at the track of a particular animal, for example), where would be the best place to put this? associatedReferences? associatedMedia? Is there another place to indicate that a link is for source data, not just an associated publication or a related image?

**Comment by tucotuco** [comment]
Yes, [dcterms:references](https://dwc.tdwg.org/terms/#dcterms:references).
