### ISSUE TITLE
Markdown formatting in Wiki

### ISSUE THREAD

**Issue by ekrimmel** [tdwg/dwc-qa#60]
Not a big problem, but an easy to fix one. Many of the headers in the wiki pages aren't showing up formatted. Probably just need a space between hashes and characters, e.g.

##header
## header

**Comment by debpaul** [comment]
@ekrimmel please feel free to edit the wiki! ;-) where you see this issue.

**Comment by pzermoglio** [comment]
@ekrimmel Thanks! It was working before just fine, not sure why formatting went obsolete, but is fixed now. Closing issue, but let us know if you find any place where we've missed correcting. Best

**Comment by ekrimmel** [comment]
@pzermoglio I agree, it's odd--I noticed because I was showing your video to someone and the formatting was how it should be when you recorded. Anyway, thanks for fixing!

@debpaul I don't have edit authority on this repo

**Comment by debpaul** [comment]
@ekrimmel aha. Perhaps we can change that.
