### ISSUE TITLE
document the existence of controlled vocab example files

### ISSUE THREAD

**Issue by ekrimmel** [tdwg/dwc-qa#96]
should we reference in the wiki that [files exist](https://github.com/tdwg/dwc-qa/tree/master/data) for GBIF/VertNet/iDigBio distinct value files illustrating the problem with not having controlled vocabularies? Or maybe it is referenced somewhere and I just don't see it...

@pzermoglio I am assigning the issue to you since CVs are your jam and you probably have thoughts on this

**Comment by pzermoglio** [comment]
Yep!
Done. Controlled Vocabularies wiki page updated with that and other changes.
Thanks @ekrimmel !
Closing this issue.
